spring:
  application:
    name: account
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8084"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
