spring:
  application:
    name: account
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:8084"
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

  # Mengizinkan actuator /info untuk mengakses env dengan prefix info
  info:
    env:
      enabled: true

#endpoints:
#  shutdown:
#    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

# Will be used for actuator /info
info:
  app:
    name: account
    description: "Microservice account for EazyBank application"
    version: "1.0.0"
