spring:
  application:
    name: config
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: classpath:config
          # search-locations: "/home/alfrendo/explorations/spring/eazybytes/spring-microservices/eazybank/private/config"
        git:
          uri: "https://github.com/alfrendo-silalahi/eazybank-config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  # Need to remove
  #rabbitmq:
    #host: localhost
    #port: 5672
    #username: guest
    #password: guest

server:
  port: 8084

encrypt:
  key: "123456789ASDFGHJKL"

# needed for Spring Cloud Bus & Spring Cloud Monitor
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
