spring:
  application:
    name: loans
  profiles:
    active: qa
  config:
    import: "optional:configserver:http://localhost:8084"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8083
