spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8084"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: read_only

  info:
    env:
      enabled: true

# Will be used for actuator info
info:
  app:
    name: gateway
    description: "API gateway for EazyBank application"
    version: "1.0.0"
