spring:
  application:
    name: loan
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8084"
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

logging:
  level:
    dev:
      alfrendosilalahi:
        eazybank:
          loan: debug

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

#endpoints:
#  shutdown:
#    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

# Will be used for actuator info
info:
  app:
    name: loan
    description: "Microservice loan for EazyBank application"
    version: "1.0.0"

# Contact
contact: 1234567890