spring:
  application:
    name: api__gateway
  config:
    import: "optional:configserver:http://localhost:8084"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      trace:
        enabled: true

      # global timeout configs
      httpclient:
        connect-timeout: 1000
        response-timeout: 1s

logging:
  level:
    dev:
      alfrendosilalahi:
        eazybank:
          gateway: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: read_only

  info:
    env:
      enabled: true

# Will be used for actuator info
info:
  app:
    name: gateway
    description: "API gateway for EazyBank application"
    version: "1.0.0"

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000