services:

  eazybank-rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: eazybank-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: ../common-config.yml
      service: network-deploy-service

  eazybank-config-server:
    build:
      context: ../../config-server
    image: 010501180401210102/eazybank-config-server:1.0.0
    container_name: eazybank-config-server
    ports:
      - "8084:8084"
    depends_on:
      eazybank-rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    extends:
      file: ../common-config.yml
      service: microservice-base-config

  eazybank-account:
    build:
      context: ../../account
    image: 010501180401210102/eazybank-account:1.0.0
    container_name: eazybank-account
    ports:
      - "8081:8081"
    depends_on:
      eazybank-config-server:
        condition: service_healthy
      eazybank-postgres:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eazybank-account
      SPRING_DATASOURCE_URL: jdbc:postgresql://eazybank-postgres:5432/account
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    extends:
      file: ../common-config.yml
      service: microservice-config-server-config

  eazybank-card:
    build:
      context: ../../card
    image: 010501180401210102/eazybank-card:1.0.0
    container_name: eazybank-card
    ports:
      - "8082:8082"
    depends_on:
      eazybank-config-server:
        condition: service_healthy
      eazybank-postgres:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eazybank-card
      SPRING_DATASOURCE_URL: jdbc:postgresql://eazybank-postgres:5432/card
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    extends:
      file: ../common-config.yml
      service: microservice-config-server-config

  eazybank-loan:
    build:
      context: ../../loan
    image: 010501180401210102/eazybank-loan:1.0.0
    container_name: eazybank-loan
    ports:
      - "8083:8083"
    depends_on:
      eazyba nk-config-server:
        condition: service_healthy
      eazybank-postgres:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eazybank-loan
      SPRING_DATASOURCE_URL: jdbc:postgresql://eazybank-postgres:5432/loans
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    extends:
      file: ../common-config.yml
      service: microservice-config-server-config

  eazybank-postgres:
    image: postgres:latest
    container_name: eazybank-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - eazybank-postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - eazybank
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  eazybank-postgres-data:

networks:
  eazybank:
    driver: "bridge"
