services:

#  eazybank-rabbitmq:
#    image: rabbitmq:3-management
#    hostname: rabbitmq
#    container_name: eazybank-rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    extends:
#      file: ../common-config.yml
#      service: network-deploy-service

  eazybank-config:
#    build:
#      context: ../../config
    image: config
    container_name: eazybank-config
    ports:
      - "8084:8084"
#    depends_on:
#      eazybank-rabbitmq:
#        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    extends:
      file: ../common-config.yml
      service: microservice-base-config

  eazybank-eureka:
#    build:
#      context: ../../eureka
    image: eureka
    container_name: eazybank-eureka
    ports:
      - "9000:9000"
    depends_on:
      eazybank-config:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eazybank-eureka
    extends:
      file: ../common-config.yml
      service: microservice-config-server-config

  eazybank-gateway:
#    build:
#      context: ../../gateway
    image: gateway
    container_name: eazybank-gateway
    ports:
      - "9090:9090"
    depends_on:
      eazybank-config:
        condition: service_healthy

    environment:
      SPRING_APPLICATION_NAME: eazybank-gateway
    extends:
      file: ../common-config.yml
      service: microservice-config-server-config

  eazybank-account:
#    build:
#      context: ../../account
    image: account
    container_name: eazybank-account
    ports:
      - "8081:8081"
    depends_on:
      eazybank-config:
        condition: service_healthy
      eazybank-postgres:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eazybank-account
      SPRING_DATASOURCE_URL: jdbc:postgresql://eazybank-postgres:5432/account
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    extends:
      file: ../common-config.yml
      service: microservice-config-server-config

  eazybank-card:
#    build:
#      context: ../../card
    image: card
    container_name: eazybank-card
    ports:
      - "8082:8082"
    depends_on:
      eazybank-config:
        condition: service_healthy
      eazybank-postgres:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eazybank-card
      SPRING_DATASOURCE_URL: jdbc:postgresql://eazybank-postgres:5432/card
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    extends:
      file: ../common-config.yml
      service: microservice-config-server-config

  eazybank-loan:
#    build:
#      context: ../../loan
    image: loan
    container_name: eazybank-loan
    ports:
      - "8083:8083"
    depends_on:
      eazybank-config:
        condition: service_healthy
      eazybank-postgres:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eazybank-loan
      SPRING_DATASOURCE_URL: jdbc:postgresql://eazybank-postgres:5432/loan
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    extends:
      file: ../common-config.yml
      service: microservice-config-server-config

  eazybank-postgres:
    image: postgres:latest
    container_name: eazybank-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - eazybank-postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.ddi
    networks:
      - eazybank
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  eazybank-postgres-data:

networks:
  eazybank:
    name: "eazybank"
    driver: "bridge"
